export const checkout=async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(error);
        
    }
}